// carData.js
export const carData = {
    "Toyota": ["Camry", "Corolla", "Prius", "RAV4", "Highlander", "Avalon", "Yaris", "Sienna", "Tacoma", "Tundra"],
    "Honda": ["Accord", "Civic", "CR-V", "Pilot", "Fit", "Insight", "Odyssey", "HR-V", "Ridgeline"],
    "Ford": ["F-150", "Mustang", "Explorer", "Focus", "Escape", "Fusion", "Edge", "Bronco", "Ranger", "Transit"],
    "Chevrolet": ["Silverado", "Malibu", "Equinox", "Impala", "Camaro", "Traverse", "Tahoe", "Suburban", "Colorado", "Trax"],
    "Nissan": ["Altima", "Sentra", "Rogue", "Versa", "Pathfinder", "Maxima", "Murano", "Frontier", "Titan", "Leaf"],
    "BMW": ["3 Series", "5 Series", "7 Series", "X3", "X5", "X7", "Z4", "4 Series", "2 Series", "i3", "i8"],
    "Mercedes-Benz": ["C-Class", "E-Class", "S-Class", "GLC", "GLE", "GLS", "A-Class", "CLA", "CLS", "G-Class"],
    "Audi": ["A3", "A4", "A6", "A8", "Q3", "Q5", "Q7", "TT", "R8", "e-tron"],
    "Volkswagen": ["Golf", "Passat", "Jetta", "Tiguan", "Atlas", "Beetle", "Arteon", "CC", "Golf GTI", "Golf R"],
    "Subaru": ["Impreza", "Legacy", "Outback", "Forester", "Crosstrek", "Ascent", "WRX", "BRZ", "XV", "Justy"],
    "Kia": ["Optima", "Sorento", "Sportage", "Soul", "Stinger", "Seltos", "Telluride", "Rio", "Niro", "Ceed"],
    "Hyundai": ["Elantra", "Sonata", "Santa Fe", "Tucson", "Accent", "Kona", "Palisade", "Veloster", "Ioniq", "Venue"],
    "Mazda": ["Mazda3", "Mazda6", "CX-3", "CX-5", "CX-9", "MX-5 Miata", "Mazda CX-30", "Mazda2", "Mazda CX-4"],
    "Volvo": ["S60", "S90", "XC40", "XC60", "XC90", "V60", "V90", "C40 Recharge", "V60 Cross Country"],
    "Jaguar": ["XE", "XF", "XJ", "F-Pace", "E-Pace", "F-Type", "I-Pace", "F-Pace SVR", "X-Type"],
    "Land Rover": ["Range Rover", "Range Rover Sport", "Range Rover Evoque", "Discovery", "Discovery Sport", "Defender"],
    "Porsche": ["911", "Cayenne", "Macan", "Panamera", "Taycan", "Boxster", "Cayman"],
    "Acura": ["ILX", "TLX", "RLX", "MDX", "RDX", "NSX"],
    "Infiniti": ["Q50", "Q60", "QX50", "QX60", "QX80", "Q70"],
    "Buick": ["Encore", "Enclave", "Envision", "LaCrosse", "Regal", "Envision", "Encore GX", "Enclave GX"],
    "Cadillac": ["Escalade", "XT4", "XT5", "XT6", "CT4", "CT5", "CT6", "XT4"],
    "Mini": ["Cooper", "Cooper S", "Countryman", "Clubman", "Convertible", "John Cooper Works", "Paceman"],
    "Tesla": ["Model S", "Model 3", "Model X", "Model Y", "Roadster", "Cybertruck"],
    "Fiat": ["500", "500X", "500L", "124 Spider", "Panda"],
    "Jeep": ["Wrangler", "Grand Cherokee", "Compass", "Renegade", "Cherokee", "Gladiator"],
    "Genesis": ["G70", "G80", "G90", "GV70", "GV80"],
    "Alfa Romeo": ["Giulia", "Stelvio", "4C"],
    "Mitsubishi": ["Outlander", "Eclipse Cross", "Mirage", "ASX", "Lancer", "Outlander Sport", "Galant"],
    "Dodge": ["Charger", "Challenger", "Durango", "Journey", "Grand Caravan"],
    "Saab": ["9-3", "9-5", "9-4X"], 
    "Smart": ["Fortwo", "Forfour"],
    "Suzuki": ["Swift", "Vitara", "Jimny", "SX4", "Ciaz"],
    "Lincoln": ["Navigator", "Corsair", "Aviator", "Nautilus", "MKZ", "MKC"],
    "RAM": ["1500", "2500", "3500", "ProMaster", "ProMaster City"],
    "Scion": ["tC", "xB", "xD", "iM", "FR-S"], 
    "Pontiac": ["Firebird", "G6", "Grand Prix", "Solstice", "Torrent"],
    "Saturn": ["S-Series", "Vue", "Aura", "Ion", "Sky"],
    "Hummer": ["H1", "H2", "H3"], 
    "Lexus": ["IS", "ES", "GS", "LS", "NX", "RX", "GX", "LX", "RC", "LC"],
    "Chrysler": ["300", "Pacifica", "Voyager", "Sebring"],
  };
  